name: OpenWrt-CI

on:
  schedule:
    - cron: 0 12 * * 5
  release:
    types: [published]
  watch:
    types: started

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

#      - name: luci-app-clash
#        run: |
#          cd package
#          mkdir luci-app-clash
#          cd luci-app-clash
#          git clone https://github.com/frainzy1477/luci-app-clash.git

      - name: luci-app-openclash
        run: |
          cd package
          mkdir luci-app-openclash
          cd luci-app-openclash
          git clone https://github.com/vernesong/OpenClash.git    

      - name: luci-app-serverchan
        run: |
          cd package
          mkdir luci-app-serverchan
          cd luci-app-serverchan
          git clone https://github.com/tty228/luci-app-serverchan.git

      - name: luci-theme-argon
        run: |
          cd package/lean
          rm -rf luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git

      - name: luci-app-vssr
        run: |
          cd package/lean
          git clone https://github.com/jerrykuku/lua-maxminddb.git
          git clone https://github.com/jerrykuku/luci-app-vssr.git  

      - name: luci-app-dnsfilter
        run: |
          cd package
          mkdir luci-app-dnsfilter
          cd luci-app-dnsfilter
          git clone https://github.com/garypang13/luci-app-dnsfilter.git

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_AMULE_CRYPTOPP_STATIC_LINKING=y
          CONFIG_ATH10K_THERMAL=y
          CONFIG_EFI_IMAGES=y
          # CONFIG_OPENSSL_ENGINE_BUILTIN is not set
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_acme=y
          # CONFIG_PACKAGE_amule is not set
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_blkid=y
          # CONFIG_PACKAGE_boost-chrono is not set
          # CONFIG_PACKAGE_boost-random is not set
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_collectd=y
          CONFIG_PACKAGE_collectd-mod-cpu=y
          CONFIG_PACKAGE_collectd-mod-interface=y
          CONFIG_PACKAGE_collectd-mod-iwinfo=y
          CONFIG_PACKAGE_collectd-mod-load=y
          CONFIG_PACKAGE_collectd-mod-memory=y
          CONFIG_PACKAGE_collectd-mod-network=y
          CONFIG_PACKAGE_collectd-mod-rrdtool=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_grub2-efi=y
          # CONFIG_PACKAGE_icu is not set
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kcptun-client=y
          # CONFIG_PACKAGE_kmod-crypto-user is not set
          CONFIG_PACKAGE_kmod-gre=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-raid6=y
          CONFIG_PACKAGE_kmod-lib-xor=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-md-raid0=y
          CONFIG_PACKAGE_kmod-md-raid1=y
          CONFIG_PACKAGE_kmod-md-raid10=y
          CONFIG_PACKAGE_kmod-md-raid456=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sit=y
          # CONFIG_PACKAGE_kmod-sound-hda-codec-hdmi is not set
          # CONFIG_PACKAGE_kmod-sound-hda-intel is not set
          # CONFIG_PACKAGE_kmod-sound-i8x0 is not set
          CONFIG_PACKAGE_kmod-thermal=y
          CONFIG_PACKAGE_libattr=y
          # CONFIG_PACKAGE_libbfd is not set
          # CONFIG_PACKAGE_libcryptopp is not set
          # CONFIG_PACKAGE_libdb47 is not set
          # CONFIG_PACKAGE_libdouble-conversion is not set
          # CONFIG_PACKAGE_libffi is not set
          CONFIG_PACKAGE_libiconv-full=y
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libopenssl-devcrypto=y
          # CONFIG_PACKAGE_libpcre2-16 is not set
          # CONFIG_PACKAGE_libpng is not set
          CONFIG_PACKAGE_librrd1=y
          # CONFIG_PACKAGE_libupnp is not set
          # CONFIG_PACKAGE_libwxbase is not set
          # CONFIG_PACKAGE_libzstd is not set
          CONFIG_PACKAGE_lsblk=y
          CONFIG_PACKAGE_luci-app-acme=y
          # CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_linear=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_raid456=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_mdadm=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-dnsfilter=y
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-jd-dailybonus=y
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-app-rclone=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-softethervpn=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-softethervpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-relay=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_mdadm=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_parted=y
          CONFIG_PACKAGE_pptpd=y
          CONFIG_PACKAGE_proxychains-ng=y
          # CONFIG_PACKAGE_python is not set
          # CONFIG_PACKAGE_python-base is not set
          # CONFIG_PACKAGE_python-codecs is not set
          # CONFIG_PACKAGE_python-compiler is not set
          # CONFIG_PACKAGE_python-ctypes is not set
          # CONFIG_PACKAGE_python-db is not set
          # CONFIG_PACKAGE_python-decimal is not set
          # CONFIG_PACKAGE_python-distutils is not set
          # CONFIG_PACKAGE_python-email is not set
          # CONFIG_PACKAGE_python-gdbm is not set
          # CONFIG_PACKAGE_python-light is not set
          # CONFIG_PACKAGE_python-logging is not set
          # CONFIG_PACKAGE_python-multiprocessing is not set
          # CONFIG_PACKAGE_python-ncurses is not set
          # CONFIG_PACKAGE_python-openssl is not set
          # CONFIG_PACKAGE_python-pydoc is not set
          # CONFIG_PACKAGE_python-sqlite3 is not set
          # CONFIG_PACKAGE_python-unittest is not set
          # CONFIG_PACKAGE_python-xml is not set
          # CONFIG_PACKAGE_qBittorrent is not set
          # CONFIG_PACKAGE_qt5-core is not set
          # CONFIG_PACKAGE_qt5-network is not set
          # CONFIG_PACKAGE_qt5-xml is not set
          # CONFIG_PACKAGE_rblibtorrent is not set
          CONFIG_PACKAGE_relayd=y
          CONFIG_PACKAGE_rrdtool1=y
          CONFIG_PACKAGE_smartmontools=y
          CONFIG_PACKAGE_socat=y
          CONFIG_PACKAGE_softethervpn5-bridge=y
          CONFIG_PACKAGE_softethervpn5-client=y
          CONFIG_PACKAGE_softethervpn5-libs=y
          CONFIG_PACKAGE_softethervpn5-server=y
          CONFIG_PACKAGE_sqm-scripts=y
          CONFIG_PACKAGE_srelay=y
          CONFIG_PACKAGE_tc=y
          CONFIG_PACKAGE_uclibcxx=y
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          # CONFIG_v2ray-plugin_INCLUDE_GOPROXY is not set
          # CONFIG_XRAY_CORE_COMPRESS_GOPROXY is not set
          # CONFIG_UnblockNeteaseMusicGo_INCLUDE_GOPROXY is not set
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
